tk_variant:
  - xft  # [linux]
  - noxft
# Required for UniformTypeIdentifiers
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.0"                 # [osx and x86_64]

# 2024/03 We are trying to avoid a full rebuild of zlib
# but we need to test a few key packages for compatibility first
# https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5443
zlib:         # [linux]
  - '1.2'     # [linux]
  - '1.3'     # [linux]
